# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Geome installation tasks
  when: geome_enabled | bool
  tags:
    - setup-all
    - setup-geome
    - install-all
    - install-geome
  block:
    - name: Validate Geome configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Geome
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Geome uninstallation tasks
  when: not geome_enabled | bool
  tags:
    - setup-all
    - setup-geome
  block:
    - name: Uninstall Geome
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
