# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Reitti installation tasks
  when: reitti_enabled | bool
  tags:
    - setup-all
    - setup-reitti
    - install-all
    - install-reitti
  block:
    - name: Validate Reitti configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Reitti
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Reitti uninstallation tasks
  when: not reitti_enabled | bool
  tags:
    - setup-all
    - setup-reitti
  block:
    - name: Uninstall Reitti
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
